BlockNesting:
  Max: 5

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

HandleExceptions:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ParameterLists:
  Max: 12

AsciiComments:
  Enabled: false

Lambda:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

AndOr:
  Enabled: false
